---
title: Studying Development of Psychopathology Across the Lifespan
shorttitle: Psychopathology Development Across Lifespan
author:
  - given: Isaac T.
    family: Petersen
    orcid: 0000-0003-3072-6673
    email: isaac-t-petersen@uiowa.edu
    corresponding: true
    role:
      - conceptualization
      - data curation
      - analysis
      - funding
      - investigation
      - methodology
      - project administration
      - resources
      - software
      - supervision
      - validation
      - visualization
      - writing
      - editing
    affiliations:
      - name: University of Iowa
        department: Department of Psychological and Brain Sciences
        address: G60 Psychological and Brain Sciences Building
        city: Iowa City
        region: IA
        postal-code: 52242
  - given: Zachary
    family: Demko
    orcid: 0000-0002-5717-6205
    email: zachary-demko@uiowa.edu
    corresponding: false
    role:
      - conceptualization
      - data curation
      - analysis
      - investigation
      - methodology
      - software
      - editing
    affiliations:
      - name: University of Iowa
        department: Department of Psychological and Brain Sciences
        address: G60 Psychological and Brain Sciences Building
        city: Iowa City
        region: IA
        postal-code: 52242
  - given: Megan
    family: Schumer
    orcid: 0009-0009-5488-6541
    email: megan-schumer@uiowa.edu
    corresponding: false
    role:
      - editing
    affiliations:
      - name: University of Iowa
        department: Department of Psychological and Brain Sciences
        address: G60 Psychological and Brain Sciences Building
        city: Iowa City
        region: IA
        postal-code: 52242
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    #study-registration: "The study hypotheses, methods, and analysis plan were
    #  preregistered: [LINK]."
    data-sharing: "The data for the present study are published online: [LINK]."
    related-report: ~
    conflict-of-interest: "We have no conflicts of interest to disclose. The 
      present study was approved by the University of Iowa Institutional Review
      Board (Study #: INSERT). The authors complied with APA ethical standards
      in the treatment of participants."
    financial-support: "I.P. was funded by Grant HD098235 from the Eunice 
      Kennedy Shriver National Institute of Child Health and Human Development.
      Any opinions, findings, and conclusions or recommendations expressed in 
      this material are those of the authors and do not necessarily reflect the 
      views of the National Institutes of Health."
    gratitude: "We thank Jordan L. Harris and Alexis Hosch for their help
      identifying measures of externalizing problems and transcribing and
      coding their content."
  correspondence-note: "Correspondence concerning this article should be
    addressed to Isaac T. Petersen, University of Iowa, G60 Psychological and
    Brain Sciences Building, Iowa City, IA 52242.
    Email: isaac-t-petersen@uiowa.edu"
abstract: "The field has not adequately studied individuals' development of
  psychopathology across the lifespan, instead taking a piecewise approach to
  development, limiting our understanding of lifespan development and the
  origins of psychopathology. We describe why this is the case—beyond logistical
  challenges. First, diagnostic and taxonomic systems do not define
  psychopathology constructs from a developmental perspective. A developmental
  perspective is crucial because psychopathology constructs often have earlier
  origins than their full clinical presentation, and forms of psychopathology
  frequently show changes in behavioral manifestation across development
  (heterotypic continuity). Second, current assessments do not adequately
  capture these changes in behavioral manifestation. Third, traditional scoring
  systems do not allow charting individuals' change over time in the face of
  changing behavioral manifestation. Fourth, assessments are not well-suited for
  capturing individual differences, despite the dimensional nature of
  psychopathology. We propose solutions to these challenges by introducing a
  developmental scaling framework for psychopathology. Using externalizing
  psychopathology as an example, we draw on our content analysis of
  externalizing measures, as well as lessons from the study of other constructs
  across lengthy developmental periods. Addressing these challenges will allow
  charting individuals' trajectories of psychopathology across the lifespan and
  identifying risk and protective factors that influence developmental courses."
impact-statement: ~
keywords:
  - psychopathology
  - lifespan development
  - longitudinal trajectories
  - heterotypic continuity
  - externalizing behavior problems
word-count: false
floatsintext: true
numbered-lines: false
mask: false
no-ampersand-parenthetical: false
meta-analysis: true
lang: en-US
blank-lines-above-title: 2
blank-lines-above-author-note: 2
bibliography: references.bib
date: last-modified
citation:
  #type: article-journal
  #container-title: TITLE OF JOURNAL
  #volume: INSERT
  #issue: INSERT
  #issued: YEAR
  #doi: INSERT
  url: https://devpsylab.github.io/studying-psychopathology-development-lifespan/
---

<!-- The introduction should not have a level-1 heading such as Introduction. -->

***NOTE: this manuscript is in progress of being drafted—it is incomplete.***

When entrenched, psychopathology is costly and difficult to treat [@Insel2008; @Wakschlag2019].
Understanding its developmental origins is therefore crucial for preventing later, more severe psychopathology.
Developmental science seeks to build a bridge that spans the lifespan—from infancy to older adulthood—and not just transitory periods in people's lives.
However, the field has not adequately studied individuals' development of psychopathology across the lifespan, instead taking a piecewise approach to development that focuses on narrower age ranges.
The focus on narrow age ranges restricts our ability to understand development across important transitions, such as puberty, school entry, and entry into parenthood, thus limiting our understanding of lifespan development and the origins of psychopathology.
In this paper, we describe reasons why this is the case—beyond logistical challenges of time and money.
And we propose solutions to these challenges by introducing a developmental scaling framework for psychopathology.
Using externalizing psychopathology as an example, we draw on our content analysis of over 270 externalizing measures, as well as lessons from the study of other constructs such as academic and cognitive skills across lengthy developmental periods.

# The Goal

A key goal of developmental science is to understand how people develop across the lifespan.
A variety of methods, including cross-sectional and longitudinal designs, could be leveraged for this purpose.
In a cross-sectional design, people are assessed at one timepoint.
Cross-sectional designs provide the ability to cheaply and quickly assess a wide age range, providing a snapshot at a particular point in time.
Cross-sectional designs may inform our understanding of general normative patterns of change—such as the typical pattern of cognitive growth and decline across the lifespan.

However, cross-sectional designs have key limitations.
Cross-sectional designs do not allow examining individuals' change over time.
Individuals show considerable heterogeneity in level and change across time in many constructs, so cross-sectional designs may obscure diverse patterns of change.
<!-- Discuss heterogeneity of cognitive decline. -->
Moreover, in a cross-sectional study, any apparent age-related differences in a construct could reflect cohort differences instead of developmental changes.
For example, average differences in stress between 5-year-olds and 10-year-olds could reflect the differing experiences that the 10-year-olds shared—such as going to school during the Coronavirus pandemic.

<!-- Findings from cross-sectional studies do not always converge with findings from longitudinal studies. -->

However, even cross-sectional work spanning the lifespan is not often conducted.

In a longitudinal design, the same individuals are followed across time.
A longitudinal design allows examining individuals' change across time.
However, as we describe [later](#sec-potential-confounds-of-change), longitudinal designs have potential confounds of change.

# The Problem/Obstacle

# Reasons for the Problem

Beyond logistical challenges of time and money, there are several key reasons why psychology has failed to study people's development of psychopathology, longitudinally, across the lifespan.
First, diagnostic and taxonomic systems do not define psychopathology constructs from a developmental perspective.
A developmental perspective is crucial because psychopathology constructs often have earlier origins than their full clinical presentation, and forms of psychopathology frequently show changes in behavioral manifestation across development (heterotypic continuity).
Second, current assessments do not adequately capture these changes in behavioral manifestation.
Third, traditional scoring systems do not allow charting individuals' change over time in the face of changing behavioral manifestation.
Fourth, current assessments are not well-suited for capturing the full range of individual differences, despite the dimensional nature of psychopathology.
Fifth, as a result of these limitations, current assessments are not well-suited for capturing individuals' change over time.

Below, we describe these reasons in detail.
The first reason represents problems with our constructs.
The remaining reasons represent problems with existing assessments and traditional scoring systems.

## Problems of our Constructs

### Lack of a Developmental Perspective

## Problems of Existing Assessments and Traditional Scoring Systems

<!-- Mismatch of theory and method/assessment -->

### Do Not Adequately Capture Constructs' Change in Behavioral Manifestation Across Development

### Do Not Allow Charting Individuals' Change Over Time When the Construct Changes in Behavioral Manifestation

### Not Well-Suited For Capturing the Full Range of Individual Differences

<!-- Likert-Type responses -->

### Not Well-Suited for Capturing Individuals' Change Over Time

## Example: Externalizing Psychopathology

# Solution: A Developmental Scaling Framework

# Other Key Challenges to Address

## Potential Confounds of Change {#sec-potential-confounds-of-change}

### Practice Effects

### Period and Cohort Effects

### Measurement Error

### Change in Meaning of the Scores

## Factorial Invariance Across Time

## Obsolescence of Items and Measures

# Conclusion

Addressing these challenges will allow charting individuals' trajectories of psychopathology across the lifespan and identifying risk and protective factors that influence their developmental courses.
Doing so is critical for understanding how psychopathology develops, when to intervene, and how to most effectively prevent psychopathology.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# This Section Is an Appendix {#apx-a}

# Another Appendix {#apx-b}
